import { NextResponse } from "next/server";
import { jsPDF } from "jspdf";

export async function GET() {
  const doc = new jsPDF();

  // Header banner
  doc.setFillColor(10, 20, 40);
  doc.rect(0, 0, 210, 35, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.text("HEALIX BIOLABS", 20, 20);
  doc.setFontSize(11);
  doc.text("AI GENOMIC DIAGNOSTIC REPORT", 20, 28);

  // Metadata box
  doc.setTextColor(0, 0, 0);
  doc.setDrawColor(180);
  doc.rect(15, 45, 180, 35);
  doc.setFontSize(12);
  doc.text("Report ID: HX-2026-001", 20, 55);
  doc.text("Generated: 12 May 2026", 20, 63);
  doc.text("AI Confidence: 97.35%", 20, 71);

  // Section title
  doc.setFontSize(16);
  doc.text("Executive Summary", 20, 95);
  doc.setFontSize(11);
  doc.text(
    "This genomic assessment identifies oncogenic signatures across high-risk biomarkers with strong predictive confidence.",
    20,
    105,
    { maxWidth: 170 }
  );

  // Analysis table style
  doc.setFontSize(14);
  doc.text("Biomarker Analysis", 20, 130);
  doc.rect(20, 138, 170, 55);
  doc.text("BRCA1 ............ 31%", 30, 150);
  doc.text("TP53 ............. 24%", 30, 160);
  doc.text("EGFR ............. 18%", 30, 170);
  doc.text("PIK3CA ........... 12%", 30, 180);
  doc.text("KRAS ............. 8%", 30, 190);

  // Page 2
  doc.addPage();

  doc.setFillColor(10, 20, 40);
  doc.rect(0, 0, 210, 25, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(18);
  doc.text("Clinical Interpretation", 20, 16);

  doc.setTextColor(0, 0, 0);
  doc.setFontSize(12);
  doc.text(
    "Elevated BRCA1 and TP53 expression patterns indicate increased genomic instability. Clinical validation and sequencing follow-up recommended.",
    20,
    50,
    { maxWidth: 170 }
  );

  doc.setFontSize(14);
  doc.text("Recommendations", 20, 90);
  doc.setFontSize(11);
  doc.text("• Immediate molecular sequencing", 25, 105);
  doc.text("• Targeted biomarker verification", 25, 115);
  doc.text("• Oncology specialist review", 25, 125);

  doc.setFontSize(10);
  doc.text("Generated by Healix Explainable Genomic Intelligence Engine", 20, 270);

  const pdf = doc.output("arraybuffer");

  return new NextResponse(pdf, {
    headers: {
      "Content-Type": "application/pdf",
      "Content-Disposition": 'attachment; filename="healix-report.pdf"',
    },
  });
}